# -*- coding: utf-8 -*-
"""gdv_torsion_invariants.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqtrWuuPINzi8gjw2W8XXUvwAQ5V6ksF
"""

import sympy as sp

sp.init_printing()

t, x, y, z = sp.symbols('t x y z', real=True)
coords = [t, x, y, z]

a = sp.Function('a')(t)
c = sp.Function('c')(t)
b = sp.Function('b')(t, x, y, z)

beta = sp.Function('beta')(t, x, y, z)
gamma = 1 / sp.sqrt(1 - beta**2)

Wx = b*x
Wy = b*y
Wz = b*z

eta = sp.diag(-1, 1, 1, 1)
eta_diag = [-1, 1, 1, 1]

e = sp.Matrix([
    [c,   0, 0, 0],
    [Wx,  a, 0, 0],
    [Wy,  0, a, 0],
    [Wz,  0, 0, a]
])

E = sp.simplify(e.inv())

print("\ne^A_mu =\n")
sp.pprint(e)

print("\ne_A^mu =\n")
sp.pprint(E)

g = sp.zeros(4)

for mu in range(4):
    for nu in range(4):
        expr = 0
        for A in range(4):
            for B in range(4):
                expr += eta[A, B]*e[A, mu]*e[B, nu]
        g[mu, nu] = sp.simplify(expr)

print("\ng_mu_nu =\n")
sp.pprint(g)

print("\ng_0i terms:\n")
print("g_01 =")
sp.pprint(sp.simplify(g[0, 1]))
print("\ng_02 =")
sp.pprint(sp.simplify(g[0, 2]))
print("\ng_03 =")
sp.pprint(sp.simplify(g[0, 3]))

curl_xy = sp.simplify(sp.diff(Wy, x) - sp.diff(Wx, y))
curl_xz = sp.simplify(sp.diff(Wz, x) - sp.diff(Wx, z))
curl_yz = sp.simplify(sp.diff(Wz, y) - sp.diff(Wy, z))

print("\nIntegrability obstruction:\n")

print("partial_x W_y - partial_y W_x =")
sp.pprint(curl_xy)

print("\npartial_x W_z - partial_z W_x =")
sp.pprint(curl_xz)

print("\npartial_y W_z - partial_z W_y =")
sp.pprint(curl_yz)

T_up = {}

for A in range(4):
    for B in range(4):
        for C in range(4):

            expr = 0

            for mu in range(4):
                for nu in range(4):

                    bare = sp.diff(e[A, nu], coords[mu]) - sp.diff(e[A, mu], coords[nu])
                    expr += E[mu, B]*E[nu, C]*bare

            T_up[(A, B, C)] = sp.simplify(expr)

T_low = {}

for A in range(4):
    for B in range(4):
        for C in range(4):
            T_low[(A, B, C)] = sp.simplify(eta_diag[A]*T_up[(A, B, C)])

print("\nNonzero tangent torsion components before boost:\n")

for key, val in T_low.items():
    if val != 0:
        print(f"T_{key} =")
        sp.pprint(val)
        print()

def raise_all(Tabc, A, B, C):
    return eta_diag[A]*eta_diag[B]*eta_diag[C]*Tabc[(A, B, C)]

def invariant_I1(Tabc):
    expr = 0
    for A in range(4):
        for B in range(4):
            for C in range(4):
                expr += Tabc[(A, B, C)] * raise_all(Tabc, A, B, C)
    return sp.simplify(expr)

def invariant_I2(Tabc):
    expr = 0
    for A in range(4):
        for B in range(4):
            for C in range(4):
                expr += Tabc[(A, B, C)] * eta_diag[C]*eta_diag[B]*eta_diag[A]*Tabc[(C, B, A)]
    return sp.simplify(expr)

def torsion_vector_lower(Tup):
    Tv = {}
    for A in range(4):
        expr = 0
        for B in range(4):
            expr += Tup[(B, B, A)]
        Tv[A] = sp.simplify(expr)
    return Tv

def vector_norm(Tv):
    expr = 0
    for A in range(4):
        expr += eta_diag[A]*Tv[A]**2
    return sp.simplify(expr)

def axial_vector_squared(Tabc):
    Aup = {}
    for A in range(4):
        expr = 0
        for B in range(4):
            for C in range(4):
                for D in range(4):
                    eps_up = -sp.LeviCivita(A, B, C, D)
                    expr += eps_up * Tabc[(B, C, D)]
        Aup[A] = sp.simplify(expr / 6)

    A2 = 0
    for A in range(4):
        A2 += eta_diag[A]*Aup[A]**2

    return sp.simplify(A2), Aup

I1 = invariant_I1(T_low)
I2 = invariant_I2(T_low)

Tv = torsion_vector_lower(T_up)
Tv2 = vector_norm(Tv)

A2, Aup = axial_vector_squared(T_low)

TEGR = sp.simplify(sp.Rational(1,4)*I1 + sp.Rational(1,2)*I2 - Tv2)

print("\nBefore boost:\n")

print("I1 = T_abc T^abc =")
sp.pprint(I1)

print("\nI2 = T_abc T^cba =")
sp.pprint(I2)

print("\nT_a =")
for A in range(4):
    print(f"T_{A} =")
    sp.pprint(Tv[A])

print("\nT_a T^a =")
sp.pprint(Tv2)

print("\nA^a =")
for A in range(4):
    print(f"A^{A} =")
    sp.pprint(Aup[A])

print("\nA_a A^a =")
sp.pprint(A2)

print("\nTEGR torsion scalar T =")
sp.pprint(TEGR)

Lambda = sp.Matrix([
    [gamma, -gamma*beta, 0, 0],
    [-gamma*beta, gamma, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

Lambda_inv = sp.Matrix([
    [gamma, gamma*beta, 0, 0],
    [gamma*beta, gamma, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

Tboost_up = {}

for A in range(4):
    for B in range(4):
        for C in range(4):

            expr = 0

            for D in range(4):
                for E1 in range(4):
                    for F in range(4):

                        expr += (
                            Lambda[A, D]
                            * Lambda_inv[E1, B]
                            * Lambda_inv[F, C]
                            * T_up[(D, E1, F)]
                        )

            Tboost_up[(A, B, C)] = sp.simplify(expr)

Tboost_low = {}

for A in range(4):
    for B in range(4):
        for C in range(4):
            Tboost_low[(A, B, C)] = sp.simplify(eta_diag[A]*Tboost_up[(A, B, C)])

I1_boost = invariant_I1(Tboost_low)
I2_boost = invariant_I2(Tboost_low)

Tv_boost = torsion_vector_lower(Tboost_up)
Tv2_boost = vector_norm(Tv_boost)

A2_boost, Aup_boost = axial_vector_squared(Tboost_low)

TEGR_boost = sp.simplify(
    sp.Rational(1,4)*I1_boost
    + sp.Rational(1,2)*I2_boost
    - Tv2_boost
)

print("\nAfter boost with spin connection included:\n")

print("I1' =")
sp.pprint(I1_boost)

print("\nI2' =")
sp.pprint(I2_boost)

print("\nT'_a =")
for A in range(4):
    print(f"T'_{A} =")
    sp.pprint(Tv_boost[A])

print("\nT'_a T'^a =")
sp.pprint(Tv2_boost)

print("\nA'^a =")
for A in range(4):
    print(f"A'^{A} =")
    sp.pprint(Aup_boost[A])

print("\nA'_a A'^a =")
sp.pprint(A2_boost)

print("\nTEGR torsion scalar T' =")
sp.pprint(TEGR_boost)

print("\nInvariant differences:\n")

print("I1' - I1 =")
sp.pprint(sp.simplify(I1_boost - I1))

print("\nI2' - I2 =")
sp.pprint(sp.simplify(I2_boost - I2))

print("\nT'_a T'^a - T_a T^a =")
sp.pprint(sp.simplify(Tv2_boost - Tv2))

print("\nA'_a A'^a - A_a A^a =")
sp.pprint(sp.simplify(A2_boost - A2))

print("\nT' - T =")
sp.pprint(sp.simplify(TEGR_boost - TEGR))