# -*- coding: utf-8 -*-
"""gdv_lorentz_covarience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbGfxzABh7JHMzlI8mFleoY0wnmvFrfP
"""

import sympy as sp

# Coordinates
t, x1, x2, x3, eps = sp.symbols("t x1 x2 x3 eps")
coords = [t, x1, x2, x3]
basis_names = ["dt", "dx1", "dx2", "dx3"]

a = sp.Function("a")(t)
b = sp.Function("b")(t, x1, x2, x3)
xs = [x1, x2, x3]


class Form:
    def __init__(self, terms=None):
        self.terms = {}
        if terms:
            for k, v in terms.items():
                v = sp.simplify(v)
                if v != 0:
                    self.terms[tuple(k)] = v

    def __add__(self, other):
        out = dict(self.terms)
        for k, v in other.terms.items():
            out[k] = sp.simplify(out.get(k, 0) + v)
            if out[k] == 0:
                out.pop(k, None)
        return Form(out)

    __radd__ = __add__

    def __neg__(self):
        return Form({k: -v for k, v in self.terms.items()})

    def __sub__(self, other):
        return self + (-other)

    def __mul__(self, c):
        return Form({k: sp.simplify(c * v) for k, v in self.terms.items()})

    __rmul__ = __mul__

    def wedge(self, other):
        out = {}
        for I, c in self.terms.items():
            for J, d in other.terms.items():
                if set(I) & set(J):
                    continue

                L = list(I) + list(J)
                inv = sum(
                    1
                    for p in range(len(L))
                    for q in range(p + 1, len(L))
                    if L[p] > L[q]
                )
                sign = (-1) ** inv
                K = tuple(sorted(L))
                out[K] = sp.simplify(out.get(K, 0) + sign * c * d)

        return Form(out)

    def d(self):
        out = Form()
        for I, c in self.terms.items():
            for mu, q in enumerate(coords):
                dc = sp.diff(c, q)
                if dc != 0:
                    out += Form({(mu,): dc}).wedge(Form({I: 1}))
        return out

    def trunc(self, order=1):
        out = {}
        for k, v in self.terms.items():
            v = sp.expand(v)
            keep = 0
            for term in sp.Add.make_args(v):
                deg = term.as_powers_dict().get(eps, 0)
                if deg <= order:
                    keep += term
            out[k] = sp.simplify(keep)
        return Form(out)

    def __repr__(self):
        if not self.terms:
            return "0"
        parts = []
        for k, v in sorted(self.terms.items()):
            name = "∧".join(basis_names[i] for i in k)
            parts.append(f"({sp.sstr(v)}) {name}")
        return " + ".join(parts)


def oneform(i):
    return Form({(i,): 1})


dt = oneform(0)
dx = [oneform(1), oneform(2), oneform(3)]

# Shift
W = [eps * b * xs[i] for i in range(3)]

# Original tetrad
e0 = dt
ei = [a * dx[i] + W[i] * dt for i in range(3)]

# Original torsion: omega = 0
T0 = e0.d()
Ti = [e.d() for e in ei]

print("Original T^0:")
print(T0)

for i in range(3):
    print(f"Original T^{i+1}:")
    print(Ti[i])

# Infinitesimal boost beta_i = -W_i
beta = [-W[i] for i in range(3)]

# Transformed tetrad, linear order
ep0 = (dt + sum([beta[i] * ei[i] for i in range(3)], Form())).trunc(1)
epi = [(beta[i] * e0 + ei[i]).trunc(1) for i in range(3)]

print("\nTransformed e'^0:")
print(ep0)

for i in range(3):
    print(f"Transformed e'^{i+1}:")
    print(epi[i])

# Spin connection: omega'^i_0 = -d beta_i = dW_i
omega_i0 = [(-Form({(): beta[i]}).d()).trunc(1) for i in range(3)]
omega_0i = omega_i0

for i in range(3):
    print(f"\nomega'^{i+1}_0:")
    print(omega_i0[i])

# Transformed torsion
Tp0 = (
    ep0.d()
    + sum([omega_0i[i].wedge(epi[i]) for i in range(3)], Form())
).trunc(1)

Tpi = [
    (epi[i].d() + omega_i0[i].wedge(ep0)).trunc(1)
    for i in range(3)
]

print("\nTransformed T'^0:")
print(Tp0)

for i in range(3):
    print(f"Transformed T'^{i+1}:")
    print(Tpi[i])

# Compare spatial torsion
print("\nCheck T'^i - T^i:")
for i in range(3):
    print(f"T'^{i+1} - T^{i+1} =")
    print((Tpi[i] - Ti[i]).trunc(1))

# Covariance check
Tcov0 = sum([beta[i] * Ti[i] for i in range(3)], Form()).trunc(1)

print("\nCovariance check for T'^0:")
print("T'^0 =")
print(Tp0)
print("beta_i T^i =")
print(Tcov0)
print("difference =")
print((Tp0 - Tcov0).trunc(1))
