# -*- coding: utf-8 -*-
"""gdv_diffeomorphsim_gauge_test_torsion_scalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIICfzmn32dSTdvN7mqhNe5Ptfvm5qaX
"""

import sympy as sp

sp.init_printing()

t, x, y, z = sp.symbols('t x y z', real=True)

coords = [t, x, y, z]

a = sp.Function('a')(t)
c = sp.Function('c')(t)

b = sp.Function('b')(t, x, y, z)

H = sp.diff(a, t) / a

Wx = b*x
Wy = b*y
Wz = b*z

eta = sp.diag(-1, 1, 1, 1)

e = sp.Matrix([

    [c,   0, 0, 0],

    [Wx,  a, 0, 0],
    [Wy,  0, a, 0],
    [Wz,  0, 0, a]

])

print("\ne^A_mu =\n")
sp.pprint(e)

einv = sp.simplify(e.inv())

print("\ne_A^mu =\n")
sp.pprint(einv)

g = sp.zeros(4)

for mu in range(4):
    for nu in range(4):

        expr = 0

        for A in range(4):
            for B in range(4):

                expr += eta[A,B]*e[A,mu]*e[B,nu]

        g[mu,nu] = sp.simplify(expr)

print("\ng_mu_nu =\n")
sp.pprint(g)

print("\ng_0i terms:\n")

print("g_01 =")
sp.pprint(sp.simplify(g[0,1]))

print("\ng_02 =")
sp.pprint(sp.simplify(g[0,2]))

print("\ng_03 =")
sp.pprint(sp.simplify(g[0,3]))

curl_xy = sp.simplify(sp.diff(Wy, x) - sp.diff(Wx, y))
curl_xz = sp.simplify(sp.diff(Wz, x) - sp.diff(Wx, z))
curl_yz = sp.simplify(sp.diff(Wz, y) - sp.diff(Wy, z))

print("\nIntegrability test for removing g_0i:\n")

print("∂x Wy - ∂y Wx =")
sp.pprint(curl_xy)

print("\n∂x Wz - ∂z Wx =")
sp.pprint(curl_xz)

print("\n∂y Wz - ∂z Wy =")
sp.pprint(curl_yz)

T = {}

for rho in range(4):
    for mu in range(4):
        for nu in range(4):

            expr = 0

            for A in range(4):

                expr += einv[rho,A]*(
                    sp.diff(e[A,nu], coords[mu])
                    -
                    sp.diff(e[A,mu], coords[nu])
                )

            T[(rho,mu,nu)] = sp.simplify(expr)

print("\nNonzero torsion components:\n")

for key,val in T.items():

    if val != 0:

        print(f"T^{key[0]}_{{{key[1]}{key[2]}}} =")
        sp.pprint(val)
        print()

Tv = [0]*4

for mu in range(4):

    expr = 0

    for nu in range(4):
        expr += T[(nu,nu,mu)]

    Tv[mu] = sp.simplify(expr)

print("\nTorsion vector T_mu:\n")

for i in range(4):

    print(f"T_{i} =")
    sp.pprint(Tv[i])
    print()

divW = sp.simplify(

    sp.diff(Wx,x)
    +
    sp.diff(Wy,y)
    +
    sp.diff(Wz,z)

)

print("\n∂_i W^i =\n")
sp.pprint(divW)

Tscalar = sp.simplify(

    6*H**2/c**2
    -
    (4*H/(a*c**2))*divW

)

print("\nTorsion scalar T =\n")
sp.pprint(Tscalar)

r = sp.symbols('r', positive=True)

br = sp.Function('b')(t,r)

radial_div = 3*br + r*sp.diff(br,r)

Tradial = sp.simplify(

    6*H**2/c**2
    -
    (4*H/(a*c**2))*radial_div

)

print("\nRadial case b(t,r):\n")

print("∂_i W^i =")
sp.pprint(radial_div)

print("\nT =")
sp.pprint(Tradial)

print("\nConclusion:\n")

print("For W_i = b(t,x,y,z) x_i, the integrability obstruction is:")
print("partial_i W_j - partial_j W_i = x_j partial_i b - x_i partial_j b.")
print("The code explicitly computes these three components above.")
print("For generic b(t,x,y,z), these expressions are not zero.")
print("Therefore the metric cross terms g_0i cannot be removed in general.")
print("Moreover, the torsion scalar depends explicitly on b and its spatial derivatives.")
print("Hence W_i = b x_i is not pure diffeomorphism gauge.")