# -*- coding: utf-8 -*-
"""radial_gdv_all.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165CkofiEWLkNp6_i0Xlo4VvRa7df5br9
"""

import sympy as sp
from sympy import Matrix, Function, symbols, sin, cos, diff, simplify, trigsimp, factor

sp.init_printing(use_unicode=True)

# ======================================================================
# COORDINATES, FUNCTIONS, PARAMETERS
# ======================================================================

t, r, th, ph = symbols("t r theta phi", real=True)
coords = [t, r, th, ph]
coord_names = ["t", "r", "theta", "phi"]
flat_names = ["0", "1", "2", "3"]

a = Function("a")(t)
c = Function("c")(t)
b = Function("b")(t, r)

beta, kappa = symbols("beta kappa", real=True)

# Physical matter variables
rho = Function("rho")(t, r)
p = Function("p")(t, r)
W = Function("W")(t, r)

eta = Matrix([
    [-1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 0],
    [ 0, 0, 0, 1],
])

# ======================================================================
# TETRAD, INVERSE TETRAD, METRIC
# ======================================================================

# e^A_mu, rows = flat index A, columns = coordinate index mu
# This tetrad contains the radial drift b(t,r) in e^1_t.
e = Matrix([
    [c,   0,   0,             0],
    [r*b, a,   0,             0],
    [0,   0,   a*r,           0],
    [0,   0,   0,   a*r*sin(th)],
])

# e_A^mu, represented as matrix rows = coordinate index mu, columns = flat index A
e_inv = simplify(e.inv())

g = simplify(e.T * eta * e)
g_inv = simplify(g.inv())
e_det = simplify(e.det())

# ======================================================================
# UTILITY PRINT FUNCTIONS
# ======================================================================

def simp(x):
    return simplify(trigsimp(x))


def print_header(title):
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


def print_subheader(title):
    print("\n" + "-" * 80)
    print(title)
    print("-" * 80)


def print_matrix_nonzero(title, matrix, upper=False):
    print_header(title)
    for i in range(4):
        for j in range(4):
            value = simp(matrix[i, j])
            if value != 0:
                symbol = "^" if upper else "_"
                print(f"g{symbol}{{{coord_names[i]}{coord_names[j]}}} = {value}")

# ======================================================================
# COVARIANT TELEPARALLEL SPIN CONNECTION
# ======================================================================

omega = {}

def set_omega(A, B, mu, value):
    omega[(A, B, mu)] = value
    omega[(B, A, mu)] = -value

set_omega(1, 2, 2, -1)
set_omega(1, 3, 3, -sin(th))
set_omega(2, 3, 3, -cos(th))

# ======================================================================
# TORSION T^A_{mu nu} AND T^rho_{mu nu}
# ======================================================================

T_flat = {}
T_coord = {}

for A in range(4):
    for mu in range(4):
        for nu in range(mu + 1, 4):
            value = diff(e[A, nu], coords[mu]) - diff(e[A, mu], coords[nu])
            for B in range(4):
                value += omega.get((A, B, mu), 0) * e[B, nu]
                value -= omega.get((A, B, nu), 0) * e[B, mu]
            value = simp(value)
            if value != 0:
                T_flat[(A, mu, nu)] = value
                T_flat[(A, nu, mu)] = -value

for rho_i in range(4):
    for mu in range(4):
        for nu in range(mu + 1, 4):
            value = 0
            for A in range(4):
                value += e_inv[rho_i, A] * T_flat.get((A, mu, nu), 0)
            value = simp(value)
            if value != 0:
                T_coord[(rho_i, mu, nu)] = value
                T_coord[(rho_i, nu, mu)] = -value

# ======================================================================
# BASIC GEOMETRY OUTPUT
# ======================================================================

print_header("TETRAD e^A_mu")
for A in range(4):
    for mu in range(4):
        if e[A, mu] != 0:
            print(f"e^{flat_names[A]}_{coord_names[mu]} = {e[A, mu]}")

print_header("INVERSE TETRAD e_A^mu")
for mu in range(4):
    for A in range(4):
        value = simp(e_inv[mu, A])
        if value != 0:
            print(f"e_{flat_names[A]}^{coord_names[mu]} = {value}")

print_matrix_nonzero("METRIC g_mu_nu", g, upper=False)
print_matrix_nonzero("INVERSE METRIC g^mu_nu", g_inv, upper=True)

print_header("DETERMINANT")
print(f"e = det(e^A_mu) = {e_det}")

print_header("LORENTZ SIGNATURE")
print(f"g_tt = {g[0, 0]}")
print("Condition: c(t)^2 - r^2*b(t,r)^2 > 0")

print_header("COVARIANT SPIN CONNECTION omega^A_{B mu}")
for key in sorted(omega):
    A, B, mu = key
    value = omega[key]
    if value != 0:
        print(f"omega^{flat_names[A]}_{flat_names[B]},{coord_names[mu]} = {value}")

print_header("NONZERO FLAT TORSION T^A_{mu nu}")
for A in range(4):
    for mu in range(4):
        for nu in range(mu + 1, 4):
            value = T_flat.get((A, mu, nu), 0)
            if value != 0:
                print(f"T^{flat_names[A]}_{{{coord_names[mu]}{coord_names[nu]}}} = {value}")

print_header("NONZERO COORDINATE TORSION T^rho_{mu nu}")
for rho_i in range(4):
    for mu in range(4):
        for nu in range(mu + 1, 4):
            value = T_coord.get((rho_i, mu, nu), 0)
            if value != 0:
                print(f"T^{coord_names[rho_i]}_{{{coord_names[mu]}{coord_names[nu]}}} = {value}")

# ======================================================================
# TORSION VECTOR AND INVARIANT I = T_mu T^mu
# ======================================================================

T_cov = {}
for mu in range(4):
    value = 0
    for nu in range(4):
        value += T_coord.get((nu, nu, mu), 0)
    T_cov[mu] = simp(value)

T_contra = {}
for mu in range(4):
    value = 0
    for nu in range(4):
        value += g_inv[mu, nu] * T_cov[nu]
    T_contra[mu] = simp(value)

I_Tvec = 0
for mu in range(4):
    I_Tvec += T_cov[mu] * T_contra[mu]
I_Tvec = simp(I_Tvec)

print_header("TORSION VECTOR T_mu = T^nu_{nu mu}")
for mu in range(4):
    print(f"T_{coord_names[mu]} = {T_cov[mu]}")

print_header("RAISED TORSION VECTOR T^mu = g^mu nu T_nu")
for mu in range(4):
    print(f"T^{coord_names[mu]} = {T_contra[mu]}")

print_header("TORSION VECTOR INVARIANT I = T_mu T^mu")
print(f"I = {I_Tvec}")

print_header("DEPENDENCE CHECK")
print(f"Contains theta: {I_Tvec.has(th)}")
print(f"Contains phi:   {I_Tvec.has(ph)}")

# ======================================================================
# LOWERED TORSION, MIXED TORSION, CONTORTION, SUPERPOTENTIAL
# ======================================================================

T_lower = {}
for rho_i in range(4):
    for mu in range(4):
        for nu in range(4):
            value = 0
            for sigma in range(4):
                value += g[rho_i, sigma] * T_coord.get((sigma, mu, nu), 0)
            value = simp(value)
            if value != 0:
                T_lower[(rho_i, mu, nu)] = value

T_mixed = {}
for mu in range(4):
    for nu in range(4):
        for rho_i in range(4):
            value = 0
            for alpha in range(4):
                value += g_inv[mu, alpha] * T_lower.get((alpha, nu, rho_i), 0)
            value = simp(value)
            if value != 0:
                T_mixed[(mu, nu, rho_i)] = value

K = {}
for mu in range(4):
    for nu in range(4):
        for rho_i in range(4):
            value = -sp.Rational(1, 2) * (
                T_mixed.get((mu, nu, rho_i), 0)
                - T_mixed.get((nu, mu, rho_i), 0)
                - T_coord.get((rho_i, mu, nu), 0)
            )
            value = simp(value)
            if value != 0:
                K[(mu, nu, rho_i)] = value

S = {}
for rho_i in range(4):
    for mu in range(4):
        for nu in range(4):
            term1 = K.get((mu, nu, rho_i), 0)

            term2 = 0
            term3 = 0

            if mu == rho_i:
                for alpha in range(4):
                    term2 += T_mixed.get((alpha, nu, alpha), 0)

            if nu == rho_i:
                for alpha in range(4):
                    term3 += T_mixed.get((alpha, mu, alpha), 0)

            value = sp.Rational(1, 2) * (term1 + term2 - term3)
            value = simp(value)
            if value != 0:
                S[(rho_i, mu, nu)] = value

print_header("NONZERO CONTORTION K^{mu nu}_{rho}")
for mu in range(4):
    for nu in range(4):
        for rho_i in range(4):
            value = K.get((mu, nu, rho_i), 0)
            if value != 0:
                print(f"K^{{{coord_names[mu]} {coord_names[nu]}}}_{{{coord_names[rho_i]}}} = {value}")

print_header("NONZERO SUPERPOTENTIAL S_rho^{mu nu}")
for rho_i in range(4):
    for mu in range(4):
        for nu in range(mu + 1, 4):
            value = S.get((rho_i, mu, nu), 0)
            if value != 0:
                print(f"S_{{{coord_names[rho_i]}}}^{{{coord_names[mu]}{coord_names[nu]}}} = {value}")

# ======================================================================
# TORSION SCALAR, LAGRANGIAN DENSITY
# ======================================================================

T_scalar = 0
for rho_i in range(4):
    for mu in range(4):
        for nu in range(4):
            T_scalar += T_coord.get((rho_i, mu, nu), 0) * S.get((rho_i, mu, nu), 0)
T_scalar = simp(T_scalar)

Lagr_density = simp(e_det * (T_scalar + beta * I_Tvec))

print_header("TORSION SCALAR T")
print(f"T = {T_scalar}")

print_header("TORSION VECTOR INVARIANT I")
print(f"I = {I_Tvec}")

print_header("LAGRANGIAN DENSITY")
print("L = e ( T + beta I )")
print()
print(Lagr_density)

# ======================================================================
# TEGR FIELD EQUATIONS
# ======================================================================

partial_S = {}
for rho_i in range(4):
    for mu in range(4):
        value = 0
        for nu in range(4):
            value += diff(e_det * S.get((rho_i, mu, nu), 0), coords[nu])
        partial_S[(rho_i, mu)] = simp(value)

TEGR_coord = {}
for rho_i in range(4):
    for mu in range(4):
        term1 = partial_S.get((rho_i, mu), 0) / e_det

        term2 = 0
        for sigma in range(4):
            for nu in range(4):
                term2 += T_coord.get((sigma, nu, rho_i), 0) * S.get((sigma, nu, mu), 0)

        term3 = T_scalar / 4 if rho_i == mu else 0

        value = simp(term1 - term2 + term3)
        if value != 0:
            TEGR_coord[(rho_i, mu)] = value

TEGR_tetrad = {}
for A in range(4):
    for mu in range(4):
        value = 0
        for rho_i in range(4):
            value += e[A, rho_i] * TEGR_coord.get((rho_i, mu), 0)
        value = simp(value)
        if value != 0:
            TEGR_tetrad[(A, mu)] = value

print_header("TEGR FIELD EQUATIONS E_A^mu")
for A in range(4):
    for mu in range(4):
        value = TEGR_tetrad.get((A, mu), 0)
        if value != 0:
            print(f"E_{flat_names[A]}^{coord_names[mu]} = {value}")

# ======================================================================
# BETA INVARIANT CONTRIBUTION Z_A^mu
# ======================================================================

Z_coord = {}
for rho_i in range(4):
    for mu in range(4):
        term_metric = sp.Rational(1, 2) * I_Tvec if rho_i == mu else 0
        term_vector = -T_contra.get(rho_i, 0) * T_cov.get(mu, 0)
        value = simp(term_metric + term_vector)
        if value != 0:
            Z_coord[(rho_i, mu)] = value

Z_tetrad = {}
for A in range(4):
    for mu in range(4):
        value = 0
        for rho_i in range(4):
            value += e[A, rho_i] * Z_coord.get((rho_i, mu), 0)
        value = simp(value)
        if value != 0:
            Z_tetrad[(A, mu)] = value

print_header("BETA INVARIANT CONTRIBUTION Z_A^mu")
for A in range(4):
    for mu in range(4):
        value = Z_tetrad.get((A, mu), 0)
        if value != 0:
            print(f"Z_{flat_names[A]}^{coord_names[mu]} = {value}")

# ======================================================================
# FULL GEOMETRIC FIELD EQUATIONS F_A^mu = E_A^mu + beta Z_A^mu
# ======================================================================

FieldEq = {}
for A in range(4):
    for mu in range(4):
        value = TEGR_tetrad.get((A, mu), 0) + beta * Z_tetrad.get((A, mu), 0)
        value = simp(value)
        if value != 0:
            FieldEq[(A, mu)] = value

print_header("FULL FIELD EQUATIONS: F_A^mu = E_A^mu + beta Z_A^mu")
for A in range(4):
    for mu in range(4):
        value = FieldEq.get((A, mu), 0)
        if value != 0:
            print(f"F_{flat_names[A]}^{coord_names[mu]} = {value}")

all_components = [
    (0, 0), (0, 1), (0, 2), (0, 3),
    (1, 0), (1, 1), (1, 2), (1, 3),
    (2, 0), (2, 1), (2, 2), (2, 3),
    (3, 0), (3, 1), (3, 2), (3, 3),
]

# ======================================================================
# PHYSICAL MATTER SECTOR
# ======================================================================

# We now include the user's intended flowing matter sector explicitly.
# In the local orthonormal/tetrad frame, impose spherical radial flow:
#
# T^(A B) =
# [ rho      rho W    0    0 ]
# [ rho W      p      0    0 ]
# [   0        0      p    0 ]
# [   0        0      0    p ]
#
# This is the spherical/radial version of
# T^{mu nu} = [[rho, rho W_x, rho W_y, rho W_z], ...]
# with W_i = W(t,r) rhat_i.

T_hat_upup = Matrix([
    [rho,    rho * W, 0, 0],
    [rho * W, p,      0, 0],
    [0,       0,      p, 0],
    [0,       0,      0, p],
])

# Lower the first flat index: T_A^B = eta_AC T^(C B)
T_hat_mixed = simp(eta * T_hat_upup)

# Project to source used by the tetrad field equations:
# Theta_A^mu = e_B^mu T_A^B
Theta_phys = {}
for A in range(4):
    for mu in range(4):
        value = 0
        for B in range(4):
            value += e_inv[mu, B] * T_hat_mixed[A, B]
        Theta_phys[(A, mu)] = simp(value)

print_header("PHYSICAL ENERGY-MOMENTUM TENSOR IN TETRAD FRAME")
print("T^(A B) =")
print(T_hat_upup)
print()
print("T_A^B = eta_AC T^(C B) =")
print(T_hat_mixed)

print_header("PROJECTED MATTER SOURCE Theta_A^mu = e_B^mu T_A^B")
for A in range(4):
    for mu in range(4):
        value = Theta_phys[(A, mu)]
        if value != 0:
            print(f"Theta_{flat_names[A]}^{coord_names[mu]} = {value}")

# ======================================================================
# FIELD EQUATIONS WITH PHYSICAL MATTER
# ======================================================================

print_header("FIELD EQUATIONS WITH PHYSICAL MATTER")
print("F_A^mu = kappa Theta_A^mu, with Theta_A^mu projected from flowing matter")

for A, mu in all_components:
    lhs = simp(FieldEq.get((A, mu), 0))
    rhs = simp(kappa * Theta_phys[(A, mu)])

    if lhs != 0 or rhs != 0:
        print_subheader(f"Component ({flat_names[A]}, {coord_names[mu]})")
        print(f"F_{flat_names[A]}^{coord_names[mu]} = kappa Theta_{flat_names[A]}^{coord_names[mu]}")
        print()
        print(lhs)
        print("=")
        print(rhs)

# ======================================================================
# ZERO / NONZERO GEOMETRIC FIELD EQUATIONS
# ======================================================================

zero_equations = []
nonzero_equations = []

for A, mu in all_components:
    lhs = simp(FieldEq.get((A, mu), 0))
    if lhs == 0:
        zero_equations.append((A, mu))
    else:
        nonzero_equations.append((A, mu))

print_header("ZERO GEOMETRIC FIELD EQUATIONS")
for A, mu in zero_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]} = 0")

print_header("NONZERO GEOMETRIC FIELD EQUATIONS")
for A, mu in nonzero_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]} != 0")

# ======================================================================
# SYMBOLIC / SHORTENED FIELD EQUATIONS
# ======================================================================

D = symbols("D", real=True)
Q = symbols("Q", real=True)
H_eff = symbols("H_eff", real=True)

adot = diff(a, t)
br = diff(b, r)
D_expr = adot - b
Q_expr = 3 * (adot - b) - r * br
H_eff_expr = simp(Q_expr / (3 * a))

replacement_rules = {
    diff(a, t) - b: D,
    3 * (diff(a, t) - b) - r * diff(b, r): Q,
    (3 * (diff(a, t) - b) - r * diff(b, r)) / (3 * a): H_eff,
}

FieldEq_symbolic = {}
for A, mu in all_components:
    value_symbolic = FieldEq.get((A, mu), 0)
    if value_symbolic != 0:
        for old, new in replacement_rules.items():
            value_symbolic = value_symbolic.subs(old, new)
    FieldEq_symbolic[(A, mu)] = simp(value_symbolic)

print_header("SYMBOLIC / SHORTENED FIELD EQUATIONS")
print("Definitions:")
print("D = adot - b")
print("Q = 3(adot - b) - r b_r")
print("H_eff = Q / (3a)")

for A, mu in all_components:
    value = FieldEq_symbolic.get((A, mu), 0)
    print_subheader(f"Component ({flat_names[A]}, {coord_names[mu]})")
    print(f"F_{flat_names[A]}^{coord_names[mu]} = {value}")

# ======================================================================
# CLASSIFICATION OF FIELD EQUATIONS
# ======================================================================

diagonal_equations = []
offdiagonal_equations = []
antisymmetric_candidates = []
constraint_equations = []
dynamic_equations = []
angular_equations = []
radial_temporal_equations = []

for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))

    if A == mu:
        diagonal_equations.append((A, mu))
    else:
        offdiagonal_equations.append((A, mu))
        antisymmetric_candidates.append((A, mu))

    has_adot = value.has(diff(a, t))
    has_addot = value.has(diff(a, t, 2))
    has_bt = value.has(diff(b, t))
    has_btt = value.has(diff(b, t, 2))
    has_br = value.has(diff(b, r))
    has_brr = value.has(diff(b, r, 2))

    has_time_derivative = has_adot or has_addot or has_bt or has_btt
    has_radial_derivative = has_br or has_brr

    if has_time_derivative:
        dynamic_equations.append((A, mu))
    else:
        constraint_equations.append((A, mu))

    if value.has(th) or value.has(sin(th)) or value.has(cos(th)):
        angular_equations.append((A, mu))

    if has_time_derivative or has_radial_derivative:
        radial_temporal_equations.append((A, mu))

print_header("CLASSIFICATION OF FIELD EQUATIONS")
print("\nDIAGONAL EQUATIONS")
print("-" * 80)
for A, mu in diagonal_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

print("\nOFF-DIAGONAL EQUATIONS")
print("-" * 80)
for A, mu in offdiagonal_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

print("\nANTISYMMETRIC-SECTOR CANDIDATES")
print("-" * 80)
for A, mu in antisymmetric_candidates:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

print("\nDYNAMIC EQUATIONS")
print("-" * 80)
for A, mu in dynamic_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

print("\nCONSTRAINT-LIKE EQUATIONS")
print("-" * 80)
for A, mu in constraint_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

print("\nANGULAR-DEPENDENT EQUATIONS")
print("-" * 80)
for A, mu in angular_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

print("\nRADIAL / TEMPORAL STRUCTURE EQUATIONS")
print("-" * 80)
for A, mu in radial_temporal_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

# ======================================================================
# PHYSICAL CLASSIFICATION WITH PROJECTED MATTER
# ======================================================================

vacuum_constraints = []
matter_sourced = []
identically_zero = []
source_zero = []
source_nonzero = []

for A, mu in all_components:
    lhs = simp(FieldEq.get((A, mu), 0))
    rhs_source = simp(Theta_phys[(A, mu)])

    if lhs == 0:
        identically_zero.append((A, mu))
    else:
        matter_sourced.append((A, mu))

    if rhs_source == 0:
        source_zero.append((A, mu))
    else:
        source_nonzero.append((A, mu))

    is_offdiag = A != mu
    has_no_second_time = not lhs.has(diff(a, t, 2)) and not lhs.has(diff(b, t, 2))

    if lhs != 0 and rhs_source == 0 and is_offdiag and has_no_second_time:
        vacuum_constraints.append((A, mu))

print_header("PHYSICAL CLASSIFICATION WITH FLOWING MATTER")

print("\nIDENTICALLY ZERO GEOMETRIC EQUATIONS")
print("-" * 80)
for A, mu in identically_zero:
    print(f"F_{flat_names[A]}^{coord_names[mu]} = 0")

print("\nNONZERO GEOMETRIC EQUATIONS")
print("-" * 80)
for A, mu in matter_sourced:
    print(f"F_{flat_names[A]}^{coord_names[mu]} = kappa Theta_{flat_names[A]}^{coord_names[mu]}")

print("\nNONZERO MATTER SOURCE COMPONENTS")
print("-" * 80)
for A, mu in source_nonzero:
    print(f"Theta_{flat_names[A]}^{coord_names[mu]} = {Theta_phys[(A, mu)]}")

print("\nZERO MATTER SOURCE COMPONENTS")
print("-" * 80)
for A, mu in source_zero:
    print(f"Theta_{flat_names[A]}^{coord_names[mu]} = 0")

print("\nCONSTRAINTS CAUSED BY ZERO SOURCE COMPONENTS")
print("-" * 80)
for A, mu in vacuum_constraints:
    print(f"F_{flat_names[A]}^{coord_names[mu]} = 0 because Theta_{flat_names[A]}^{coord_names[mu]} = 0")

# ======================================================================
# EQUATIONS SENSITIVE TO DRIFT FIELD b(t,r)
# ======================================================================

b_sensitive_equations = []
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    depends_on_b = (
        value.has(b)
        or value.has(diff(b, t))
        or value.has(diff(b, r))
        or value.has(diff(b, t, r))
        or value.has(diff(b, r, 2))
    )
    if depends_on_b:
        b_sensitive_equations.append((A, mu))

print_header("EQUATIONS SENSITIVE TO THE DRIFT FIELD b(t,r)")
for A, mu in b_sensitive_equations:
    value = simp(FieldEq.get((A, mu), 0))
    print_subheader(f"F_{flat_names[A]}^{coord_names[mu]}")
    print(value)

# ======================================================================
# SPHERICAL SYMMETRY TESTS
# ======================================================================

F_2_theta = simp(FieldEq.get((2, 2), 0))
F_3_phi = simp(FieldEq.get((3, 3), 0))

symmetry_test_raw = simp(F_3_phi - sin(th)**2 * F_2_theta)

print_header("SPHERICAL SYMMETRY TEST")
print("\nTest required by text:")
print("F_3^phi - sin(theta)^2 F_2^theta")
print("-" * 80)
print(symmetry_test_raw)

if symmetry_test_raw == 0:
    print("\nResult: PASSED")
else:
    print("\nResult: FAILED or tetrad-index comparison is not directly metric-projected")

FieldEq_coord = {}
for rho_i in range(4):
    for mu in range(4):
        value = 0
        for A in range(4):
            value += e_inv[rho_i, A] * FieldEq.get((A, mu), 0)
        value = simp(value)
        if value != 0:
            FieldEq_coord[(rho_i, mu)] = value

G_theta_theta = simp(FieldEq_coord.get((2, 2), 0))
G_phi_phi = simp(FieldEq_coord.get((3, 3), 0))

symmetry_test_coord = simp(G_phi_phi - G_theta_theta)

print_header("COORDINATE-PROJECTED ANGULAR TEST")
print("\nG_phi^phi - G_theta^theta")
print("-" * 80)
print(symmetry_test_coord)

if symmetry_test_coord == 0:
    print("\nCoordinate-projected angular isotropy: PASSED")
else:
    print("\nCoordinate-projected angular isotropy: FAILED")

print_header("THETA / PHI DEPENDENCE IN FIELD EQUATIONS")
angular_dependence = []
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    if value.has(th) or value.has(ph):
        angular_dependence.append((A, mu, value))

if len(angular_dependence) == 0:
    print("No explicit theta or phi dependence found.")
else:
    for A, mu, value in angular_dependence:
        print_subheader(f"F_{flat_names[A]}^{coord_names[mu]}")
        print(value)

print_header("TRIGONOMETRIC CONTAMINATION CHECK")
trig_contaminated = []
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    value_string = str(value)
    has_trig_artifact = (
        "tan(theta)" in value_string
        or "cot(theta)" in value_string
        or "sin(theta)" in value_string
        or "cos(theta)" in value_string
    )
    if has_trig_artifact:
        trig_contaminated.append((A, mu, value))

if len(trig_contaminated) == 0:
    print("No trigonometric contamination detected.")
else:
    for A, mu, value in trig_contaminated:
        print_subheader(f"F_{flat_names[A]}^{coord_names[mu]}")
        print(value)

print_header("SCALAR SPHERICAL SYMMETRY CHECK")
print("\nTorsion scalar T:")
print(T_scalar)
print(f"Contains theta: {T_scalar.has(th)}")
print(f"Contains phi:   {T_scalar.has(ph)}")

print("\nInvariant I = T_mu T^mu:")
print(I_Tvec)
print(f"Contains theta: {I_Tvec.has(th)}")
print(f"Contains phi:   {I_Tvec.has(ph)}")

if not T_scalar.has(th) and not T_scalar.has(ph) and not I_Tvec.has(th) and not I_Tvec.has(ph):
    print("\nCovariant formalism successfully removed angular contamination.")
else:
    print("\nResidual angular contamination detected.")

# ======================================================================
# DYNAMIC ANALYSIS
# ======================================================================

print_header("DYNAMIC ANALYSIS")
time_evolution_equations = []
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    has_time_structure = (
        value.has(diff(a, t))
        or value.has(diff(a, t, 2))
        or value.has(diff(b, t))
        or value.has(diff(b, t, 2))
        or value.has(diff(b, t, r))
    )
    if has_time_structure:
        time_evolution_equations.append((A, mu, value))

print("\nTIME-EVOLUTION EQUATIONS")
print("-" * 80)
for A, mu, value in time_evolution_equations:
    print(f"\nF_{flat_names[A]}^{coord_names[mu]}")
    print(value)

print_header("DRIFT-FIELD CONSTRAINT ANALYSIS")
drift_constraints = []
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    depends_on_b = value.has(b) or value.has(diff(b, r)) or value.has(diff(b, t))
    no_second_order = not value.has(diff(a, t, 2)) and not value.has(diff(b, t, 2))
    if depends_on_b and no_second_order:
        drift_constraints.append((A, mu, value))

for A, mu, value in drift_constraints:
    print_subheader(f"Potential drift constraint: F_{flat_names[A]}^{coord_names[mu]}")
    print(value)
    print("=")
    print(kappa * Theta_phys[(A, mu)])

# ======================================================================
# VACUUM LIMIT
# ======================================================================

print_header("VACUUM LIMIT")
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    if value != 0:
        print_subheader(f"Vacuum equation F_{flat_names[A]}^{coord_names[mu]} = 0")
        print(value)

# ======================================================================
# FLRW LIMIT : b(t,r) -> 0
# ======================================================================

print_header("FLRW LIMIT : b(t,r) -> 0")
FLRW_limit = {}
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    value = value.subs(b, 0)
    value = value.subs(diff(b, r), 0)
    value = value.subs(diff(b, t), 0)
    value = value.subs(diff(b, r, 2), 0)
    value = simp(value)
    FLRW_limit[(A, mu)] = value

for A, mu in all_components:
    value = FLRW_limit[(A, mu)]
    if value != 0:
        print_subheader(f"FLRW limit of F_{flat_names[A]}^{coord_names[mu]}")
        print(value)

print_header("PROPAGATING DRIFT MODE TEST")
contains_bt = False
contains_btt = False
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    if value.has(diff(b, t)):
        contains_bt = True
    if value.has(diff(b, t, 2)):
        contains_btt = True

print(f"Contains b_t   : {contains_bt}")
print(f"Contains b_tt  : {contains_btt}")

if contains_btt:
    print("\nDrift field appears to be propagating.")
elif contains_bt:
    print("\nDrift field has first-order dynamics / constrained evolution.")
else:
    print("\nDrift field behaves like a pure constraint sector.")

# ======================================================================
# EFFECTIVE HUBBLE PARAMETER
# ======================================================================

print_header("EFFECTIVE HUBBLE PARAMETER")
print("\nDefinition of Q:")
print("Q = 3(adot - b) - r b_r")
print()
print(Q_expr)

print("\nDefinition of H_eff:")
print("H_eff = Q / (3a)")
print()
print(H_eff_expr)

H_standard = simp(diff(a, t) / a)
Delta_H = simp(H_eff_expr - H_standard)

print_header("COMPARISON WITH STANDARD HUBBLE")
print("\nStandard Hubble:")
print(H_standard)

print("\nEffective Hubble:")
print(H_eff_expr)

print("\nDeviation:")
print("Delta_H = H_eff - H")
print(Delta_H)

print_header("REWRITING INVARIANTS USING H_eff")
T_using_Heff = simp(T_scalar.subs(Q_expr, 3 * a * H_eff))
I_using_Heff = simp(I_Tvec.subs(Q_expr, 3 * a * H_eff))

print("\nTorsion scalar rewritten:")
print(T_using_Heff)

print("\nInvariant I rewritten:")
print(I_using_Heff)

print_header("FRIEDMANN-LIKE EQUATION")
F00 = simp(FieldEq.get((0, 0), 0))
F00_Heff = simp(F00.subs(Q_expr, 3 * a * H_eff))
print("\nF_0^t equation:")
print(F00_Heff)
print("=")
print(kappa * Theta_phys[(0, 0)])

print_header("FLRW LIMIT OF H_eff")
H_eff_FLRW = simp(H_eff_expr.subs(b, 0))
print(H_eff_FLRW)

if simp(H_eff_FLRW - diff(a, t) / a) == 0:
    print("\nCorrect FLRW limit recovered.")
else:
    print("\nFLRW limit mismatch detected.")

# ======================================================================
# MEANINGFUL FIELD EQUATIONS IN H_eff VARIABLES
# ======================================================================

print_header("MEANINGFUL FIELD EQUATIONS IN H_eff VARIABLES")
H = symbols("H", real=True)
Heff = symbols("H_eff", real=True)
Dsym = symbols("D", real=True)
Qsym = symbols("Q", real=True)
Psym = symbols("P", real=True)

P_expr = b + r * br
rewrite_rules = {
    adot / a: H,
    D_expr: Dsym,
    Q_expr: Qsym,
    P_expr: Psym,
    Q_expr / (3 * a): Heff,
    Q_expr**2 / (9 * a**2): Heff**2,
    Q_expr**2 / (a**2): 9 * Heff**2,
}

def rewrite_heff(expr):
    expr = simp(expr)
    for old, new in rewrite_rules.items():
        expr = expr.subs(old, new)
    expr = simp(expr)
    expr = expr.subs(Qsym, 3 * a * Heff)
    expr = simp(expr)
    return expr

MeaningfulEq = {}
for A, mu in all_components:
    raw = simp(FieldEq.get((A, mu), 0))
    if raw != 0:
        MeaningfulEq[(A, mu)] = rewrite_heff(raw)
    else:
        MeaningfulEq[(A, mu)] = 0

for A, mu in all_components:
    value = MeaningfulEq.get((A, mu), 0)
    rhs = simp(kappa * Theta_phys[(A, mu)])
    if value != 0 or rhs != 0:
        print_subheader(f"F_{flat_names[A]}^{coord_names[mu]} = kappa Theta_{flat_names[A]}^{coord_names[mu]}")
        print(value)
        print("=")
        print(rhs)

# ======================================================================
# PHYSICAL FORM OF MAIN EQUATIONS
# ======================================================================

print_header("PHYSICAL FORM OF MAIN EQUATIONS")
main_equations = [
    (0, 0),
    (0, 1),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 2),
    (3, 3),
]

for A, mu in main_equations:
    lhs = simp(MeaningfulEq.get((A, mu), 0))
    rhs = simp(kappa * Theta_phys[(A, mu)])
    if lhs != 0 or rhs != 0:
        print_subheader(f"Main equation: F_{flat_names[A]}^{coord_names[mu]}")
        print(lhs)
        print("=")
        print(rhs)

print_header("FRIEDMANN / RADIAL / ANGULAR / CONSTRAINT SPLIT")
equation_roles = {
    (0, 0): "Energy equation / tetrad-time source",
    (0, 1): "Radial momentum source equation",
    (1, 0): "Radial energy-flow equation",
    (1, 1): "Radial pressure / acceleration equation",
    (2, 0): "Angular-time constraint",
    (2, 2): "Tangential pressure equation",
    (3, 3): "Azimuthal pressure equation",
}

for key in main_equations:
    A, mu = key
    lhs = simp(MeaningfulEq.get((A, mu), 0))
    rhs = simp(kappa * Theta_phys[(A, mu)])
    role = equation_roles.get(key, "Unclassified meaningful equation")
    if lhs != 0 or rhs != 0:
        print_subheader(f"{role}\nComponent: F_{flat_names[A]}^{coord_names[mu]}")
        print(lhs)
        print("=")
        print(rhs)

# ======================================================================
# DEGREES OF FREEDOM ANALYSIS
# ======================================================================

print_header("DEGREES OF FREEDOM ANALYSIS")
evolution_equations = []
constraint_equations = []

for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    if value == 0:
        continue

    contains_second_time = value.has(diff(a, t, 2)) or value.has(diff(b, t, 2))
    contains_first_time = value.has(diff(a, t)) or value.has(diff(b, t))

    if contains_second_time or contains_first_time:
        evolution_equations.append((A, mu, value))
    else:
        constraint_equations.append((A, mu, value))

print("\nEVOLUTION EQUATIONS")
print("-" * 80)
for A, mu, value in evolution_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")
    print()

print("\nCONSTRAINT EQUATIONS")
print("-" * 80)
for A, mu, value in constraint_equations:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")
    print()

print_header("ANTISYMMETRIC SECTOR")
antisymmetric_sector = []
for A, mu in all_components:
    if A == mu:
        continue
    value = simp(FieldEq.get((A, mu), 0))
    if value != 0:
        antisymmetric_sector.append((A, mu, value))

if len(antisymmetric_sector) == 0:
    print("Antisymmetric sector vanishes.")
else:
    for A, mu, value in antisymmetric_sector:
        print_subheader(f"Antisymmetric candidate: F_{flat_names[A]}^{coord_names[mu]}")
        print(value)
        print("=")
        print(kappa * Theta_phys[(A, mu)])

print_header("DRIFT PROPAGATION ANALYSIS")
drift_first_order = []
drift_second_order = []
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    if value.has(diff(b, t)):
        drift_first_order.append((A, mu))
    if value.has(diff(b, t, 2)):
        drift_second_order.append((A, mu))

print("\nEquations containing b_t")
print("-" * 80)
for A, mu in drift_first_order:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

print("\nEquations containing b_tt")
print("-" * 80)
for A, mu in drift_second_order:
    print(f"F_{flat_names[A]}^{coord_names[mu]}")

if len(drift_second_order) > 0:
    print("\nDrift field appears to contain propagating modes.")
elif len(drift_first_order) > 0:
    print("\nDrift field has first-order dynamics / constrained evolution.")
else:
    print("\nDrift field behaves as a pure constraint.")

print_header("EFFECTIVE EQUATION COUNT")
nonzero_count = 0
dynamic_count = 0
constraint_count = 0
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    if value != 0:
        nonzero_count += 1
        dynamic = value.has(diff(a, t)) or value.has(diff(a, t, 2)) or value.has(diff(b, t)) or value.has(diff(b, t, 2))
        if dynamic:
            dynamic_count += 1
        else:
            constraint_count += 1

print(f"Nonzero equations     : {nonzero_count}")
print(f"Dynamic equations     : {dynamic_count}")
print(f"Constraint equations  : {constraint_count}")

# ======================================================================
# FLRW CLOSURE TEST
# ======================================================================

print_header("FLRW CLOSURE TEST")
FLRW_dynamic = []
for A, mu in all_components:
    value = simp(FieldEq.get((A, mu), 0))
    value = value.subs(b, 0)
    value = value.subs(diff(b, r), 0)
    value = value.subs(diff(b, t), 0)
    value = simp(value)
    if value != 0:
        FLRW_dynamic.append((A, mu, value))

for A, mu, value in FLRW_dynamic:
    print_subheader(f"FLRW equation: F_{flat_names[A]}^{coord_names[mu]}")
    print(value)

# ======================================================================
# MINKOWSKI, TEGR, STATIC, HOMOGENEOUS DRIFT LIMITS
# ======================================================================

print_header("MINKOWSKI LIMIT")
minkowski_rules = {
    a: 1,
    c: 1,
    b: 0,
    diff(a, t): 0,
    diff(a, t, 2): 0,
    diff(b, t): 0,
    diff(b, r): 0,
    diff(b, t, 2): 0,
    diff(b, r, 2): 0,
}

T_minkowski = simp(T_scalar.subs(minkowski_rules))
I_minkowski = simp(I_Tvec.subs(minkowski_rules))

print("\nTorsion scalar:")
print(T_minkowski)

print("\nInvariant:")
print(I_minkowski)

print("\nField equations in Minkowski limit")
print("-" * 80)
for A, mu in all_components:
    value = FieldEq.get((A, mu), 0)
    value = simp(value.subs(minkowski_rules)) if value != 0 else 0
    if value != 0:
        print(f"\nF_{flat_names[A]}^{coord_names[mu]}")
        print(value)

print_header("TEGR LIMIT : beta -> 0")
TEGR_limit = {}
for A, mu in all_components:
    value = FieldEq.get((A, mu), 0)
    value = simp(value.subs(beta, 0)) if value != 0 else 0
    TEGR_limit[(A, mu)] = value

for A, mu in all_components:
    value = TEGR_limit[(A, mu)]
    if value != 0:
        print_subheader(f"TEGR equation F_{flat_names[A]}^{coord_names[mu]}")
        print(value)

print_header("STATIC LIMIT")
static_rules = {
    diff(a, t): 0,
    diff(a, t, 2): 0,
}
for A, mu in all_components:
    value = FieldEq.get((A, mu), 0)
    value = simp(value.subs(static_rules)) if value != 0 else 0
    if value != 0:
        print_subheader(f"Static equation F_{flat_names[A]}^{coord_names[mu]}")
        print(value)

print_header("HOMOGENEOUS DRIFT LIMIT")
homogeneous_rules = {
    diff(b, r): 0,
    diff(b, r, 2): 0,
}
for A, mu in all_components:
    value = FieldEq.get((A, mu), 0)
    value = simp(value.subs(homogeneous_rules)) if value != 0 else 0
    if value != 0:
        print_subheader(f"Homogeneous-drift equation F_{flat_names[A]}^{coord_names[mu]}")
        print(value)

# ======================================================================
# DETERMINANT, SIGNATURE, FINAL SCALAR CONTAMINATION CHECK
# ======================================================================

print_header("DETERMINANT ANALYSIS")
print("\nDeterminant:")
print(e_det)

print("\nFactorized determinant:")
print(factor(e_det))

print("""
Consistency requires:

det(e) != 0

otherwise the tetrad becomes singular.
""")

print_header("SIGNATURE STABILITY")
gtt = simp(g[0, 0])
print("\ng_tt =")
print(gtt)

signature_condition = simp(c**2 - r**2 * b**2)
print("\nLorentzian condition:")
print("c^2 - r^2 b^2 > 0")
print(signature_condition)

print_header("SCALAR CONTAMINATION CHECK")
print("\nTorsion scalar contains theta:")
print(T_scalar.has(th))

print("\nInvariant contains theta:")
print(I_Tvec.has(th))

print("\nTorsion scalar contains phi:")
print(T_scalar.has(ph))

print("\nInvariant contains phi:")
print(I_Tvec.has(ph))

if not T_scalar.has(th) and not T_scalar.has(ph) and not I_Tvec.has(th) and not I_Tvec.has(ph):
    print("\nCovariant formalism successfully removed angular contamination.")
else:
    print("\nResidual angular contamination detected.")